name: Deploy Minecraft Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-west-2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init and Apply
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve
          terraform output -raw public_ip > ../ansible/ip.txt

      - name: Install Ansible and Python deps
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible python3-pip
          pip3 install boto boto3

      - name: Upload SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/minecraft-key.pem
          chmod 600 ~/.ssh/minecraft-key.pem

      - name: Generate Inventory File
        run: |
          echo "[minecraft]" > ansible/inventory.ini
          echo "$(cat ansible/ip.txt) ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/minecraft-key.pem" >> ansible/inventory.ini

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i ansible/inventory.ini ansible/install_minecraft.yml